services:

  rabbitmq-notification:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq




# Api GateWay
  # api-gateway:
  #   build:
  #     context: apiGateway/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - USER_HOST=user-service
  #     - USER_PORT=8080 
  #     - POST_HOST=post-service
  #     - POST_PORT=3000
  #     - COMMENT_HOST=comment-service
  #     - COMMENT_PORT=8000 
  #     - FOLLOWER_HOST=follower-service
  #     - FOLLOWER_PORT=3001

# UserService
  postgres-user:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=osmait
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: userService/userService/
      dockerfile: Dockerfile
    environment:
      - DB_PORT=5432
      - DB_DATABASE=my_store
      - DB_USER=osmait
      - DB_PASSWORD=admin123
      - DB_HOSTNAME=postgres-user
    ports:
      - 8080:8080
    depends_on:
      - postgres-user

# PostService

  # postgres-post:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_DB=my_store
  #     - POSTGRES_USER=osmait
  #     - POSTGRES_PASSWORD=admin123
  #   ports:
  #     - 5433:5433
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data

  post-service:
    build:
      context: PostServices/post-service/
      dockerfile: Dockerfile
    environment:
      - DB_PORT=5432
      - DB_DATABASE=my_store
      - DB_USER=osmait
      - DB_PASSWORD=admin123
      - DB_HOSTNAME=postgres-user
      - USER_URL=comment-service
    ports:
      - 3000:3000
    # depends_on:
    #   - postgres-post
 



# CommentService

  comment-service:
    build:
      context: CommentServices/
      dockerfile: Dockerfile
 
    ports:
      - 8000:8000

  # postgres-comment:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_DB=my_store
  #     - POSTGRES_USER=osmait
  #     - POSTGRES_PASSWORD=admin123
  #   ports:
  #     - 5434:5434
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data


    # Notification Service

  notification-service:
    build: 
      context: notificationService/
      dockerfile: Dockerfile
    environment:
      - HOST_RABBIT=rabbitmq-notification
    ports:
      - 8084:8084
    depends_on:
      - rabbitmq-notification
    restart: always 

# Follower Service
  follower-service:
      build: 
        context: followersService/follower-service
        dockerfile: Dockerfile
      environment:
        - DB_PORT=5432
        - DB_DATABASE=my_store
        - DB_USER=osmait
        - DB_PASSWORD=admin123
        - DB_HOSTNAME=postgres-user
        - USER_URL="http//user-service:8080"
      ports:
        - 3001:3001
      # depends_on:
      
      #   - postgres-follower
      restart: always 

  # postgres-follower:
  #     image: postgres:13
  #     environment:
  #       - POSTGRES_DB=my_store
  #       - POSTGRES_USER=osmait
  #       - POSTGRES_PASSWORD=admin123
  #     ports:
  #       - 5435:5435
  #     volumes:
  #       - ./postgres_data:/var/lib/postgresql/data


  
      
      



    

