
FROM openjdk:17-jdk-alpine
# Directorio de trabajo dentro del contenedor
WORKDIR /app

COPY . .

# Copiar el archivo JAR construido en nel directorio de trabajo



# Comando para ejecutar la aplicación Spring Boot[

CMD ./gradlew bootRun

