version: "3.2"
services:
      # Notification Service
  notification-service:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST_RABBIT=rabbitmq-notification
    ports:
      - 8083:8083
    depends_on:
      - rabbitmq-notification
    restart: always 
  rabbitmq-notification:
      image: rabbitmq:3-management-alpine
      ports:
          - 5672:5672
          - 15672:15672
      volumes:
          - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
          - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq


