version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=osmait
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 3000:3000
    depends_on:
      - postgres
    # volumes:
    #   - .:/app
    #   - "/app/node_modules"
    command: npm run start:dev
