# Define la imagen base de Python
FROM python:3.11-slim

# Instalar Poetry
RUN pip install poetry

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos necesarios a la carpeta de trabajo
COPY . .


# Instalar dependencias usando Poetry
RUN poetry install

# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 8000

# Comando para ejecutar la aplicación FastAPI
CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000","--reload"]
