spring:
  datasource:
    url: jdbc:postgresql://${env.DB_HOSTNAME}:${env.DB_PORT}/${env.DB_DATABASE}
    username: ${env.DB_USER}
    password: ${env.DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
