name: Build and Push Docker Images

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Api GateWay

      - name: Build and push apiGateway
        uses: docker/build-push-action@v4
        with:
          context: apiGateway/
          push: true
          tags: osmait/api-gateway:latest

      # User Service

      - name: Build and push userService
        uses: docker/build-push-action@v4
        with:
          context: userService/userService/
          push: true
          tags: osmait/user-service:latest

      # Post Service

      - name: Build and push postService
        uses: docker/build-push-action@v4
        with:
          context: PostServices/post-service/
          push: true
          tags: osmait/post-service:latest

      # Comment service
      - name: Build and push commentService
        uses: docker/build-push-action@v4
        with:
          context: CommentServices/
          push: true
          tags: osmait/comment-service:latest
